# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html

stages:
  - build

build-job:
  stage: build
  variables:
    CI_REGISTRY_IMAGE_NAME: operator
  tags:
    - k8s
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:latest --tag $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$CI_REGISTRY_IMAGE_NAME:latest